name: covivre
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: 1.6.22

  flutter_switch: ^0.1.4

  cupertino_icons: ^1.0.0

  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - lib/assets/img/arrow.png
  fonts:
    - family: Heaters
      fonts:
        - asset: lib/assets/fonts/Heaters.otf
    - family: FaturaMedium
      fonts:
        - asset: lib/assets/fonts/futura-pt-medium.otf
  
