name: covivre
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  flutter_localizations:
#    sdk: flutter
  path_provider: 1.6.24
  percent_indicator: "^2.1.7+2"
  flutter_switch: ^0.1.4
  syncfusion_flutter_sliders: ^18.3.47-beta
  charts_flutter: ^0.9.0
  syncfusion_flutter_charts: ^18.1.48
  date_utils: ^0.1.0
  flutter_staggered_grid_view: "^0.3.2"
  story_view: ^0.12.4
  cupertino_icons: ^1.0.0
  easy_localization: ^2.3.3
  easy_localization_loader:
    git: https://github.com/aissat/easy_localization_loader.git
  shared_preferences: ^0.5.8


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
 intl: ^0.17.0-nullsafety.2



flutter:
  uses-material-design: true
  assets:
    - lib/assets/img/arrow.png
    - lib/assets/img/Calque34.png
    - lib/assets/img/Calque33.png
    - lib/assets/img/Location.png
    - lib/assets/img/DeadVirusBackground.png
    - lib/assets/img/FightIcon.png
    - lib/assets/img/IAmIcon.png
    - lib/assets/img/BackgroundImage.png
    - lib/assets/img/Info.png
    - lib/assets/img/Bad.png
    - lib/assets/img/Good.png
    - lib/assets/img/Hard.png
    - lib/assets/img/Middle.png
    - lib/assets/img/CoVivre.png
    - lib/assets/img/IamFillOff.png
    - lib/assets/img/safe-shield-protection.png
    - lib/assets/img/safe-shield-protection2.png
    - lib/assets/img/PopupImage.png
    - lib/assets/img/map_Fond.png
    - lib/assets/img/VirusLightGreen.png
    - lib/assets/img/RiskArrow.png 
    - lib/assets/img/VulnerableArrow.png
    - lib/assets/img/circleCovid.png
    - lib/assets/img/ShareIcon.png
    - lib/assets/img/SanitizerIcon.png
    - lib/assets/img/MaskIcon.png
    - lib/assets/img/HandsIcon.png
    - lib/assets/img/DistanceIcon.png
    - lib/assets/img/firstPage.png
    - lang/


  fonts:
    - family: Heaters
      fonts:
        - asset: lib/assets/fonts/Heaters.otf
    - family: FaturaMedium
      fonts:
        - asset: lib/assets/fonts/futura-pt-medium.otf
    - family: FaturaBold
      fonts:
        - asset: lib/assets/fonts/fatura-pt-bold.ttf
    - family: FaturaBoldOBbli
      fonts:
        - asset: lib/assets/fonts/futura-pt-bold-oblique.otf
    - family: FaturaExtraBold
      fonts:
        - asset: lib/assets/fonts/futura-pt-extrabold.otf
    - family: FaturaHeavy
      fonts:
        - asset: lib/assets/fonts/FuturaPT-Heavy.ttf
    - family: FaturaDemi
      fonts:
        - asset: lib/assets/fonts/futura-pt-demi.ttf
    - family: FaturaBook
      fonts:
        - asset: lib/assets/fonts/futura-pt-book.ttf
    - family: FaturaLight
      fonts:
        - asset: lib/assets/fonts/Futura-Light.ttf


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
